#!/bin/sh
cd /home/ychoi/ATOM/build/
./ExperimentAnalysisPlot.out L1F2X
./ExperimentAnalysisPlot.out L1F3X
./ExperimentAnalysisPlot.out L1F4X
./ExperimentAnalysisPlot.out L1REFX
./ExperimentAnalysisPlot.out L1F2O
./ExperimentAnalysisPlot.out L1F3O
./ExperimentAnalysisPlot.out L1F4O
./ExperimentAnalysisPlot.out L1REFO
./ExperimentAnalysisPlot.out L3F2X
./ExperimentAnalysisPlot.out L3F3X
./ExperimentAnalysisPlot.out L3F4X
./ExperimentAnalysisPlot.out L3REFX
./ExperimentAnalysisPlot.out L3F2O
./ExperimentAnalysisPlot.out L3F3O
./ExperimentAnalysisPlot.out L3F4O
./ExperimentAnalysisPlot.out L3REFO
./ExperimentAnalysisPlot.out L7F2X
./ExperimentAnalysisPlot.out L7F3X
./ExperimentAnalysisPlot.out L7F4X
./ExperimentAnalysisPlot.out L7REFX
./ExperimentAnalysisPlot.out L7F2O
./ExperimentAnalysisPlot.out L7F3O
./ExperimentAnalysisPlot.out L7F4O
./ExperimentAnalysisPlot.out L7REFO
./ExperimentAnalysisPlot.out L20F2X
./ExperimentAnalysisPlot.out L20F3X
./ExperimentAnalysisPlot.out L20F4X
./ExperimentAnalysisPlot.out L20REFX
./ExperimentAnalysisPlot.out L20F2O
./ExperimentAnalysisPlot.out L20F3O
./ExperimentAnalysisPlot.out L20F4O
./ExperimentAnalysisPlot.out L20REFO