./analysis.sh 1mm_1phi_alphagamma
./analysis.sh 1mm_2phi_alphagamma
./analysis.sh 1mm_3phi_alphagamma
./analysis.sh 1mm_4phi_alphagamma
./analysis.sh 1mm_7phi_alphagamma
./analysis.sh 3mm_2phi_alphagamma
./analysis.sh 3mm_3phi_alphagamma
./analysis.sh 3mm_4phi_alphagamma
./analysis.sh 3mm_7phi_alphagamma
./analysis.sh 7mm_2phi_alphagamma
./analysis.sh 7mm_3phi_alphagamma
./analysis.sh 7mm_4phi_alphagamma
./analysis.sh 7mm_7phi_alphagamma
./analysis.sh 20mm_2phi_alphagamma
./analysis.sh 20mm_3phi_alphagamma
./analysis.sh 20mm_4phi_alphagamma
./analysis.sh 20mm_7phi_alphagamma
./analysis.sh 1mm_1phi_gamma
./analysis.sh 1mm_2phi_gamma
./analysis.sh 1mm_3phi_gamma
./analysis.sh 1mm_4phi_gamma
./analysis.sh 1mm_7phi_gamma
./analysis.sh 3mm_2phi_gamma
./analysis.sh 3mm_3phi_gamma
./analysis.sh 3mm_4phi_gamma
./analysis.sh 3mm_7phi_gamma
./analysis.sh 7mm_2phi_gamma
./analysis.sh 7mm_3phi_gamma
./analysis.sh 7mm_4phi_gamma
./analysis.sh 7mm_7phi_gamma
./analysis.sh 20mm_2phi_gamma
./analysis.sh 20mm_3phi_gamma
./analysis.sh 20mm_4phi_gamma
./analysis.sh 20mm_7phi_gamma